#!/usr/bin/env -S deno run --allow-read
// Copyright 2018-2026 the Deno authors. MIT license.
//
// Oden op-coverage completeness manifest (LLP 0001 Phase 0).
//
// Enumerates two things that together define the capsec mediation surface:
//   1. the capsec-mediated permission checks — every `oden_capsec_decide(...)`
//      call site, by (family, action) and enclosing fn, in the permission layer;
//   2. the op-body pre-check *skips* — every `query_read_all()` call site (the
//      fast paths that bypass the permission container when read is fully
//      granted), which capsec forces closed while armed.
//
// The manifest is committed. `--check` regenerates it and diffs against the
// committed copy, exiting non-zero on drift — so a new upstream op that touches a
// mediated resource, or a new op-body skip, is a loud rebase delta rather than a
// silent coverage gap.
//
// Self-contained: uses only Deno built-ins (the fork's vendored std may be
// absent). Run from `fork/deno`: `deno run --allow-read tools/oden/coverage_manifest.ts [--check]`.
// @ref llp/0001-adding-capability-security-to-deno.plan.md

const ROOT = new URL("../../", import.meta.url).pathname;
const MANIFEST = ROOT + "tools/oden/op_coverage.manifest.md";

// Directories scanned for op-body skips. Kept explicit so the scan is stable.
const SKIP_SCAN_DIRS = ["ext", "runtime", "libs"];
const MEDIATION_FILE = "runtime/permissions/lib.rs";

function* walk(dir: string): Generator<string> {
  let entries: Deno.DirEntry[];
  try {
    entries = [...Deno.readDirSync(dir)];
  } catch {
    return;
  }
  entries.sort((a, b) => (a.name < b.name ? -1 : 1));
  for (const e of entries) {
    const p = dir + "/" + e.name;
    if (e.isDirectory) {
      if (e.name === "target" || e.name === "node_modules") continue;
      yield* walk(p);
    } else if (e.isFile && p.endsWith(".rs")) {
      yield p;
    }
  }
}

// --- 1. mediated (family, action) pairs + enclosing fn -----------------------
function collectMediation(): string[] {
  const src = Deno.readTextFileSync(ROOT + MEDIATION_FILE);
  const lines = src.split("\n");
  let currentFn = "<module>";
  const found = new Set<string>();
  const fnRe = /\bfn\s+([a-z0-9_]+)\s*(?:<[^>]*>)?\s*\(/;
  const decideRe =
    /oden_capsec_decide\(\s*OdenFamily::([A-Za-z]+)\s*,\s*"([a-z]+)"/;
  for (const line of lines) {
    const fnM = line.match(fnRe);
    if (fnM) currentFn = fnM[1];
    const dM = line.match(decideRe);
    if (dM) {
      const family = dM[1].toLowerCase();
      const action = dM[2];
      found.add(`${family}:${action}\tvia ${currentFn}()`);
    }
  }
  // Standalone capsec checks that don't go through oden_capsec_decide.
  if (src.includes("fn oden_capsec_check_worker_create")) {
    found.add("worker:create\tvia oden_capsec_check_worker_create()");
  }
  return [...found].sort();
}

// --- 2. op-body pre-check skips (query_read_all call sites) -------------------
function collectSkips(): string[] {
  const skips: string[] = [];
  for (const d of SKIP_SCAN_DIRS) {
    for (const file of walk(ROOT + d.replace(/\/$/, ""))) {
      const rel = file.slice(ROOT.length);
      const src = Deno.readTextFileSync(file);
      const lines = src.split("\n");
      for (let i = 0; i < lines.length; i++) {
        // Call sites, not the definition (`pub fn query_read_all`).
        if (
          lines[i].includes("query_read_all()") &&
          !lines[i].includes("fn query_read_all")
        ) {
          skips.push(`${rel}:${i + 1}`);
        }
      }
    }
  }
  return skips.sort();
}

function render(): string {
  const mediation = collectMediation();
  const skips = collectSkips();
  const out: string[] = [];
  out.push("# Oden op-coverage manifest (generated)");
  out.push("");
  out.push(
    "Generated by `tools/oden/coverage_manifest.ts`. Do not edit by hand —",
  );
  out.push("run the generator and commit. Drift fails the rebase canary.");
  out.push("");
  out.push("## Capsec-mediated permission checks (family:action via fn)");
  out.push("");
  for (const m of mediation) out.push(`- ${m}`);
  out.push("");
  out.push("## Op-body pre-check skips (query_read_all call sites)");
  out.push("");
  out.push(
    "These bypass the permission container when read is fully granted; capsec",
  );
  out.push("forces `query_read_all()` false while armed. Each site must remain");
  out.push("covered by the layer-2-independence proof.");
  out.push("");
  for (const s of skips) out.push(`- ${s}`);
  out.push("");
  return out.join("\n");
}

const rendered = render();
if (Deno.args.includes("--check")) {
  let committed = "";
  try {
    committed = Deno.readTextFileSync(MANIFEST);
  } catch {
    console.error("op-coverage manifest missing; run the generator.");
    Deno.exit(1);
  }
  if (committed.trimEnd() !== rendered.trimEnd()) {
    console.error(
      "op-coverage manifest DRIFT — regenerate and review:\n" +
        "  deno run --allow-read tools/oden/coverage_manifest.ts > tools/oden/op_coverage.manifest.md",
    );
    Deno.exit(1);
  }
  console.log("op-coverage manifest: up to date");
} else {
  console.log(rendered);
}
