#!/usr/bin/env -S deno run --allow-read
// Copyright 2018-2026 the Deno authors. MIT license.
//
// Oden script-creation inventory (LLP 0001 Phase 0 / script-creation coverage).
//
// Every path that creates a script V8 will run must either register the script's
// id to a principal (so op-boundary attribution can key on it) or fail closed
// (quarantine). This inventory records each path, its status, and the source
// marker that keeps the status honest. `--check` asserts every load-bearing
// marker is still present — so removing a registration or a seal key is a loud
// failure, not a silent attribution regression.
//
// Self-contained (Deno built-ins only). Run from `fork/deno`.
// @ref llp/0001-adding-capability-security-to-deno.plan.md ; ../phase0-script-creation-coverage.md

const ROOT = new URL("../../", import.meta.url).pathname;

type Row = {
  path: string; // the script-creation mechanism
  status:
    | "registered"
    | "quarantine-by-design"
    | "blocked-rusty_v8"
    | "owed";
  note: string;
  // Source invariants that must hold for the status to be true. Each is
  // [file, substring]; --check fails if the substring is absent.
  markers: [string, string][];
};

const INVENTORY: Row[] = [
  {
    path: "ESM modules",
    status: "registered",
    note: "script id registered to the module locator at instantiation",
    markers: [[
      "libs/core/modules/map.rs",
      "oden_register_script_locator_global",
    ]],
  },
  {
    path: "CommonJS require (core.compileFunction)",
    status: "registered",
    note:
      "compiled function's script id registered to the loader-resolved specifier",
    markers: [[
      "libs/core/ops_builtin_v8.rs",
      "oden_register_script_locator_global",
    ]],
  },
  {
    path: "compileFunction / evalContext wrappers (user reach)",
    status: "quarantine-by-design",
    note:
      "sealed off Deno[Deno.internal].core while armed so a forged specifier cannot register",
    markers: [
      ["runtime/js/99_main.js", '"compileFunction"'],
      ["runtime/js/99_main.js", '"evalContext"'],
    ],
  },
  {
    path: "eval / new Function",
    status: "blocked-rusty_v8",
    note:
      "bind fresh eval script id to caller principal; needs SetModifyCodeGenerationFromStringsCallback (absent in rusty_v8 149.4.0). Quarantines until then.",
    markers: [],
  },
  {
    path: "op_eval_context (Module.wrap / patched _compile)",
    status: "blocked-rusty_v8",
    note:
      "compiles a Script; rusty_v8 149.4.0 exposes no script_id accessor on Script/UnboundScript. Wrapper is sealed, so not a forgery vector.",
    markers: [],
  },
  {
    path: "node:vm (op_vm_create_script / op_vm_compile_function)",
    status: "quarantine-by-design",
    note:
      "caller-supplied filename is forgeable, so NOT registered; vm code quarantines (verified).",
    markers: [],
  },
  {
    path: "snapshot-baked internal scripts",
    status: "owed",
    note: "snapshot script-id registration is Phase-0/1 owed work.",
    markers: [],
  },
  {
    path: "remote / module-cache ownership",
    status: "owed",
    note: "loader ownership of remote + cached module sources is owed.",
    markers: [],
  },
];

function render(): string {
  const out: string[] = [];
  out.push("# Oden script-creation inventory (generated)");
  out.push("");
  out.push("Generated by `tools/oden/script_creation_manifest.ts`. `--check`");
  out.push("asserts each `registered`/`quarantine-by-design` marker is present.");
  out.push("");
  out.push("| mechanism | status | note |");
  out.push("| --- | --- | --- |");
  for (const r of INVENTORY) {
    out.push(`| ${r.path} | ${r.status} | ${r.note} |`);
  }
  out.push("");
  return out.join("\n");
}

if (Deno.args.includes("--check")) {
  const failures: string[] = [];
  for (const r of INVENTORY) {
    for (const [file, marker] of r.markers) {
      let src = "";
      try {
        src = Deno.readTextFileSync(ROOT + file);
      } catch {
        failures.push(`${r.path}: cannot read ${file}`);
        continue;
      }
      if (!src.includes(marker)) {
        failures.push(
          `${r.path}: marker missing in ${file} — expected \`${marker}\` ` +
            `(status "${r.status}" no longer holds)`,
        );
      }
    }
  }
  if (failures.length) {
    console.error("script-creation inventory FAILURES:");
    for (const f of failures) console.error("  - " + f);
    Deno.exit(1);
  }
  console.log("script-creation inventory: all markers present");
} else {
  console.log(render());
}
